nginx:
    build: ./nginx
    links:
        - node1:node1
    ports:
        - '80:80'
node1:
    build: ./node
    ports:
        - '8080'
    links:
        - redis
    environment:
        - 'TEST=some test env yeet'
redis:
    image: redis
    ports:
        - '6379'
